# Generated by Django 5.1.4 on 2025-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
