# Generated by Django 5.1.4 on 2025-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_icecream_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='icecream',
            name='image_url',
            field=models.ImageField(upload_to='icecreams/'),
        ),
    ]
