# Generated by Django 5.1.4 on 2025-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_payment_alter_icecream_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='image_url',
        ),
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
