# Generated by Django 5.1.4 on 2025-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_feedbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
